"""add goal owner

Revision ID: 207eef9c3f65
Revises: ea6ef1ea20b2
Create Date: 2026-06-27 22:42:48.960677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207eef9c3f65'
down_revision: Union[str, Sequence[str], None] = 'ea6ef1ea20b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goals', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'owner_id')
    # ### end Alembic commands ###
